from django.urls import path

from .views import (
    admin_dashboard_overview,
    auth_status,
    contact_details,
    dashboard_overview,
    department_dashboard_overview,
    department_placement_list_create,
    faculty_account_delete,
    faculty_account_list_create,
    faculty_password_change,
    health_check,
    hiring_list,
    internship_list,
    login_view,
    logout_view,
    placement_details_content,
    star_student_list_create,
    student_account_approve,
    student_account_list_create,
    student_password_change,
    student_list_create,
)

urlpatterns = [
    path("health/", health_check, name="health-check"),
    path("auth/login/", login_view, name="auth-login"),
    path("auth/logout/", logout_view, name="auth-logout"),
    path("auth/status/", auth_status, name="auth-status"),
    path("students/", student_list_create, name="student-list-create"),
    path("dashboard/overview/", dashboard_overview, name="dashboard-overview"),
    path("dashboard/admin/overview/", admin_dashboard_overview, name="admin-dashboard-overview"),
    path(
        "dashboard/department/overview/",
        department_dashboard_overview,
        name="department-dashboard-overview",
    ),
    path("dashboard/star-students/", star_student_list_create, name="star-student-list-create"),
    path(
        "dashboard/department-placement/",
        department_placement_list_create,
        name="department-placement-list-create",
    ),
    path("faculty-accounts/", faculty_account_list_create, name="faculty-account-list-create"),
    path(
        "faculty-accounts/change-password/",
        faculty_password_change,
        name="faculty-password-change",
    ),
    path("student-accounts/", student_account_list_create, name="student-account-list-create"),
    path(
        "student-accounts/<str:student_account_id>/approve/",
        student_account_approve,
        name="student-account-approve",
    ),
    path(
        "student-accounts/change-password/",
        student_password_change,
        name="student-password-change",
    ),
    path(
        "faculty-accounts/<str:faculty_id>/",
        faculty_account_delete,
        name="faculty-account-delete",
    ),
    path("portal/placement-details/", placement_details_content, name="placement-details-content"),
    path("portal/internships/", internship_list, name="internship-list"),
    path("portal/hirings/", hiring_list, name="hiring-list"),
    path("portal/contact/", contact_details, name="contact-details"),
]
